app-office/libreoffice notmpfs.conf
app-shells/bash O3-graphite-lto.conf
app-shells/dash O3-graphite-lto.conf
dev-lang/rust notmpfs.conf
gui-wm/gamescope nondebug.conf
llvm-core/clang notmpfs.conf
llvm-core/llvm notmpfs.conf
sys-libs/glibc conservative.conf
www-client/firefox notmpfs.conf
x11-libs/pixman O3.conf
